name: Build
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review, labeled ]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: echo "TIMESTAMP=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false

      - name: Build
        run: |
          ./gradlew build --no-configuration-cache

      - name: Publish snapshot
        if: github.ref == 'refs/heads/main'
        env:
          IS_SNAPSHOT: true

          GPG_PRIVATE_KEY: ${{ env.GPG_PRIVATE_KEY }}
          GPG_KEY_PASSWORD: ${{ env.GPG_KEY_PASSWORD }}

          SONATYPE_USERNAME: ${{ env.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ env.SONATYPE_PASSWORD }}
        run: |
          echo "Publishing snapshot"
#          TODO: make non-inert when credentials are ready
#          ./gradlew publishAllPublicationsToSonatypeSnapshotsRepository --stacktrace --no-configuration-cache
